title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io
heading_anchors: true

aux_links:
  XGen Archive: https://github.com/just-the-docs/just-the-docs-template
  XGen Docs: https://github.com/just-the-docs/just-the-docs-template
  XGen Install: https://github.com/just-the-docs/just-the-docs-template
  XGen Energy: https://github.com/just-the-docs/just-the-docs-template
  XGen Explainable: https://github.com/just-the-docs/just-the-docs-template
